# Generated by Django 5.1.3 on 2024-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_review_user_qr_delete_customuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='usuario',
            new_name='user',
        ),
    ]
